### DISCUSSION TITLE
loop over 2-dimensional array of mounts?

### DISCUSSION THREAD

**Discussion by strowi** [grafana/tanka#747] [Q&A] [answered]
Hi,

i am trying to mount a series of configmaps without writing every single mount, but somehow i am getting extra dashes which break the yaml-structure. 
The Volumes and ConfigMap are created ok, only the 
Does anyone know where my errors is/how to fix this? 

```
{
  _config+:: {
    grafana+: {
      dashboards: {
        static: {
          system: {
            'dashboardx.json': (importstr './files/provisioning/dashboards/monitoring/services/dashboards.json'),
          },
          services: {
            'dashboard1.json': (importstr './files/provisioning/dashboards/monitoring/services/dashboard1.json'),
            'dashboard2.json': (importstr './files/provisioning/dashboards/monitoring/services/dashboard2.json'),
...
```

```
 local volumeMounts = [
        [
          local dashboardName = 'grafana-dashboards-' + type + '-' + std.strReplace(name, '.json', '');
          containerVolumeMount.new(dashboardName, '/etc/grafana/provisioning/dashboards/' + type + '/' + name)
          + containerVolumeMount.withSubPath(name)
          for name in std.objectFields(instance.dashboards.static[type])
        ]
        for type in std.objectFields(instance.dashboards.static)
      ],
local volumes = [
        local dashboardName = 'grafana-dashboards-services-' + std.strReplace(name, '.json', '');
        volume.withName(dashboardName)
        + volume.mixin.configMap.withName(dashboardName) 
        for name in std.objectFields($.grafana.dashboards_static.services)
        ],
...

      deployment:
        stateful.new(
          containers=[
            ...
            + container.withVolumeMounts(volumeMounts),
            // +container.withCommand(['sh', '-c', 'sleep 30m']),
          ],
        )
        + stateful.spec.template.spec.withVolumesMixin(volumes)

```

The resulting statefulset-container contains volumemounts with an extra dash per sub-array:

``` 
       volumeMounts:
        - - mountPath: /etc/grafana/provisioning/dashboards/system/dashboardx.json
            name: grafana-dashboards-system-dashboardx
            subPath: dashboardx.json
        - - mountPath: /etc/grafana/provisioning/dashboards/services/dashboard1.json
            name: grafana-dashboards-services-dashboard1
            subPath: dashboard1.json
          - mountPath: /etc/grafana/provisioning/dashboards/services/dashboard2.json
            name: grafana-dashboards-services-dashboard2
            subPath: dashboard2.json
```

regards,
strowi
