### ISSUE TITLE
0.28.0 regression on big environments

### ISSUE THREAD

**Issue by fculpo** [grafana/tanka#1150]
Starting with 0.28.0, diffing or applying a big environment renders yaml objects on stdout and get stuck.
Need to Ctrl-C to get back to prompt.

```
> tk apply environments/envX/monitoring/prometheus/main.jsonnet

...[lots of objects]...

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 2.46.0
    tanka.dev/environment: 8c60c9becc8f74d7314b2175a3f9b7c76812ff0644cb03e2
  name: prometheus-k8s
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: web
  - interval: 30s
    port: reloader-web
  selector:
    matchLabels:
      app.kubernetes.io/component: prometheus
      app.kubernetes.io/instance: k8s
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/part-of: kube-prometheus
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.67.1
    tanka.dev/environment: 8c60c9becc8f74d7314b2175a3f9b7c76812ff0644cb03e2
  name: prometheus-operator
  namespace: monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    port: https
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: prometheus-operator
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 0.67.1

^C <- stuck here, needs Ctrl-C
```

"Smaller" envs works fine

**Comment by zerok** [comment]
Hi :) Do you perhaps have a complete example that would could use to reproduce this issue? From what version were you updating?

**Comment by fculpo** [comment]
We have a lot of sensitive infos in this env, hard to share the actual jsonnet code.

I think repro could be done via a custom env rendering a lot of object, I will try to create one with big loops

**Comment by zerok** [comment]
Thank you :) That's what I meant to suggest and not your production environment 🙂

**Comment by fculpo** [comment]
main.libsonnet

```jsonnet
local k = import 'k.libsonnet';
local role = k.rbac.v1.role;
local roleBinding = k.rbac.v1.roleBinding;
local policyRule = k.rbac.v1.policyRule;
local configMap = k.core.v1.configMap;

local namespace = 'monitoring';

{
  roles:
    [
      role.new('repro-role-' + i) +
      role.metadata.withNamespace(namespace) +
      role.withRules([
        policyRule.withApiGroups([''])
        + policyRule.withResources(['pods/portforward'])
        + policyRule.withVerbs(['create']),
        policyRule.withApiGroups([''])
        + policyRule.withResources(['pods', 'services'])
        + policyRule.withVerbs(['get', 'list']),
      ])
      for i in std.range(0, 100)
    ],

  roleBindings:
    [
      roleBinding.new('repro-rolebinding-' + i) +
      roleBinding.metadata.withNamespace(namespace) +
      roleBinding.bindRole($.roles[i]) +
      roleBinding.withSubjects([
        {
          kind: 'Group',
          name: 'repro',
        },
      ])
      for i in std.range(0, 100)
    ],

  configmaps: [
    configMap.new('repro-cm' + i) +
    configMap.metadata.withNamespace(namespace) +
    configMap.withData({
      'data.yaml': importstr 'data.yaml',
    })
    for i in std.range(0, 100)
  ],
}
```

data.yaml

```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    config: alertmanager
spec:
  inhibitRules:
    - equal:
        - namespace
      sourceMatch:
        - name: alertname
          value: InfoInhibitor
      targetMatch:
        - name: severity
          value: info
    - equal:
        - severity
      sourceMatch:
        - name: alertname
          value: KubeAggregatedAPIErrors
      targetMatch:
        - name: alertname
          value: SealedSecretsUnsealErrorHigh
  route:
    groupBy: ["namespace", "severity", "alertname", "cluster"]
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 1h
    receiver: default
    routes:
      - receiver: watchdog
        matchers:
          - name: alertname
            value: Watchdog
        repeatInterval: 5m
        groupWait: 0s
        groupInterval: 1m
      - receiver: "null"
        matchers:
          - name: alertname
            value: InfoInhibitor
  receivers:
    - name: "null"
```

output:

```
> tk-0.28 apply environments/dw/monitoring/repro/main.jsonnet

...[lots of objects]...
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    tanka.dev/environment: 98e42bf3acb98facff6140923eeaef3de75c40f773d945a6
  name: repro-rolebinding-98
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: repro-role-98
subjects:
- kind: Group
  name: repro
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    tanka.dev/environment: 98e42bf3acb98facff6140923eeaef3de75c40f773d945a6
  name: repro-rolebinding-99
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: repro-role-99
subjects:
- kind: Group
  name: repro

^C
```
