### ISSUE TITLE
tk export not working anymore in 0.11

### ISSUE THREAD

**Issue by primeroz** [grafana/tanka#319]
Hi

Using `tk export ENV DIR` fails using tanka 0.11 

```
➜  cortex git:(master) tk export environments/gcs-only /tmp/cortex
File '/tmp/cortex/v1.Namespace-cortex.yaml' already exists. Aborting

➜  cortex git:(master)  ls -la /tmp/cortex
total 0
drwxr-xr-x    2 fciocchetti  40 Jul 15 14:31 ./
drwxrwxrwt 1353 root        27K Jul 15 14:31 ../
```

the `/tmp/cortex` directory was created by tanka itself and did not exist before the command was run.

just for reference , `tk show` works fine 

```
➜  cortex git:(master) tk show --dangerous-allow-redirect environments/gcs-only  | head -n 30

apiVersion: v1
kind: Namespace
metadata:
  labels:
    tanka.dev/environment: environments.gcs-only
  name: cortex
  namespace: cortex
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    name: ingester-pdb
    tanka.dev/environment: environments.gcs-only
  name: ingester-pdb
  namespace: cortex
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      name: ingester
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    tanka.dev/environment: environments.gcs-only
  name: consul-sidekick
  namespace: cortex
---
```

**Comment by sh0rez** [comment]
Hey, I think we fixed that already on master – could you try?

And yes, we should have made a patch release 🙈

**Comment by primeroz** [comment]
Hi

Still failing for me i am afraid 

```
➜  cortex git:(master) ✗ (⎈ |gke_fc-test-loki-cortex_europe-west1_cortex-loki) rm -rf /tmp/cortex

➜  cortex git:(master) ✗ (⎈ |gke_fc-test-loki-cortex_europe-west1_cortex-loki) ~/go/bin/tk --version                               
tk version dev

➜  cortex git:(master) ✗ (⎈ |gke_fc-test-loki-cortex_europe-west1_cortex-loki) ~/go/bin/tk export environments/gcs-only /tmp/cortex
File '/tmp/cortex/v1.Namespace-cortex.yaml' already exists. Aborting

➜  cortex git:(master) ✗ (⎈ |gke_fc-test-loki-cortex_europe-west1_cortex-loki) ~/go/bin/tk show --dangerous-allow-redirect environments/gcs-only | head -n 20
apiVersion: v1
kind: Namespace
metadata:
  labels:
    tanka.dev/environment: environments.gcs-only
  name: cortex
  namespace: cortex
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    name: ingester-pdb
    tanka.dev/environment: environments.gcs-only
  name: ingester-pdb
  namespace: cortex
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
```

**Comment by sh0rez** [comment]
Could you post the resources list shown in tk status?

**Comment by primeroz** [comment]
```
Context: gke_fc-test-loki-cortex_europe-west1_cortex-loki
Cluster: gke_fc-test-loki-cortex_europe-west1_cortex-loki
Environment:
  APIServer: https://35.205.39.61
  Namespace: cortex
  DiffStrategy: native
  InjectLabels: %!s(bool=true)
Resources:
  NAMESPACE    OBJECTSPEC
  cortex       Namespace/cortex
  cortex       PodDisruptionBudget/ingester-pdb
  cortex       PodDisruptionBudget/store-gateway-pdb
  cortex       ServiceAccount/consul-sidekick
  cortex       ServiceAccount/cortex
  cortex       Secret/gateway-secret
  cortex       ConfigMap/consul
  cortex       ConfigMap/gateway-config
  cortex       ConfigMap/overrides
  cortex       ConfigMap/schema-fa9497f5acccafcc3e6019657bdc5eb1
  cortex       Role/consul-sidekick
  cortex       RoleBinding/consul-sidekick
  cortex       Service/consul
  cortex       Service/distributor
  cortex       Service/gateway
  cortex       Service/ingester
  cortex       Service/memcached
  cortex       Service/memcached-frontend
  cortex       Service/memcached-index-queries
  cortex       Service/memcached-metadata
  cortex       Service/querier
  cortex       Service/query-frontend
  cortex       Service/query-frontend-discovery
  cortex       Service/store-gateway
  cortex       Deployment/consul
  cortex       Deployment/distributor
  cortex       Deployment/gateway
  cortex       Deployment/querier
  cortex       Deployment/query-frontend
  cortex       StatefulSet/compactor
  cortex       StatefulSet/ingester
  cortex       StatefulSet/memcached
  cortex       StatefulSet/memcached-frontend
  cortex       StatefulSet/memcached-index-queries
  cortex       StatefulSet/memcached-metadata
  cortex       StatefulSet/store-gateway
```

**Comment by sh0rez** [comment]
Nothing suspicious there. How did you obtain a master build?

I'd recommend cloning and `make install`, or using

```
$ GO111MODULE=1 go get github.com/grafana/tanka/cmd/tanka@master
```

Make sure to include `@master`, otherwise you would get the latest tagged release

**Comment by primeroz** [comment]
no i built without any `@` 

when i try this command i get an error
```
➜  /tmp (⎈ |gke_mntl-gke-prod-5evh_europe-west1_vault) export GO111MODULE=on

➜  /tmp (⎈ |gke_mntl-gke-prod-5evh_europe-west1_vault) go get github.com/grafana/tanka/cmd/tanka@master
go: downloading github.com/grafana/tanka v0.11.1-0.20200707231903-70c2cb39923d
go get github.com/grafana/tanka/cmd/tanka@master: module github.com/grafana/tanka@master found (v0.11.1-0.20200707231903-70c2cb39923d), but does not contain package github.com/grafana/tanka/cmd/tanka
```

so i tried building from a git clone ( making sure i was on the master branch )

```
➜  tanka git:(master) (⎈ |gke_mntl-gke-prod-5evh_europe-west1_vault) make static
CGO_ENABLED=0 go build -ldflags='-s -w -extldflags "-static" -X main.Version=v0.11.0-1-g70c2cb3' ./cmd/tk
```

i am having the same issue though 

```
➜  bin (⎈ |gke_mntl-gke-prod-5evh_europe-west1_vault) ~/go/bin/tk --version
tk version v0.11.0-1-g70c2cb3

➜  cortex git:(master) (⎈ |gke_mntl-gke-prod-5evh_europe-west1_vault) rm -rf /tmp/cortex
➜  cortex git:(master) (⎈ |gke_mntl-gke-prod-5evh_europe-west1_vault) tk export environments/gcs-only /tmp/cortex
File '/tmp/cortex/v1.Namespace-cortex.yaml' already exists. Aborting
➜  cortex git:(master) (⎈ |gke_mntl-gke-prod-5evh_europe-west1_vault) ls /tmp/cortex
➜  cortex git:(master) (⎈ |gke_mntl-gke-prod-5evh_europe-west1_vault) ~/go/bin/tk show --dangerous-allow-redirect environments/gcs-only | head -n 20
apiVersion: v1
kind: Namespace
metadata:
  labels:
    tanka.dev/environment: environments.gcs-only
  name: cortex
  namespace: cortex
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    name: ingester-pdb
    tanka.dev/environment: environments.gcs-only
  name: ingester-pdb
  namespace: cortex
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
```
