### ISSUE TITLE
Project defaults

### ISSUE THREAD

**Issue by sh0rez** [grafana/tanka#337]
Currently, tanka has `spec.json` to control it's behavior per environment. Some of that might be general enough to be shared (diffStrategy, pruning, etc).

I propose to introduce another file, `project.json` in the projects root, with the following format:

```yaml
{
  "apiVersion": "tanka.dev/v1alpha1",
  "kind": "Project",
  "metadata": {
    "name": "<project name>"
  },
  "defaults": "<spec.json here>"
}
```

This file would also replace `tkrc.yaml` as the optional root indicator, because having a mix of yaml and json for config makes no sense
