### ISSUE TITLE
how to use a kube config context instead of ApiServer URL?

### ISSUE THREAD

**Issue by wmcnamee-tunein** [grafana/tanka#351]
my kube config file looks like this:

```yaml
clusters:
- cluster:
    certificate-authority-data: <REDACTED>
    server: https://<REDACTED>.sk1.us-west-2.eks.amazonaws.com
  name: arn:aws:eks:us-west-2:<REDACTED>:cluster/myserver
users:
- name: arn:aws:eks:us-west-2:<REDACTED>:cluster/myserver
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - us-west-2
      - eks
      - get-token
      - --cluster-name
      - myserver
      command: aws
      env:
      - name: AWS_PROFILE
        value: myprofile
contexts:
- context:
    cluster: arn:aws:eks:us-west-2:<REDACTED>:cluster/myserver
    user: arn:aws:eks:us-west-2:<REDACTED>:cluster/myserver
  name: myserver

... more ...
```

I'm not sure how to get tanka to use my config
