### ISSUE TITLE
tanka not add repo to chartfile

### ISSUE THREAD

**Issue by dfang** [grafana/tanka#417]
for this traefik [chart](https://github.com/traefik/traefik-helm-chart/)

tk tool charts add traefik/traefik@9.10.1 will add requires, but i had to traefik repo to repositories to make it work, otherwise can not find chart

```
directory: charts
repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: traefik
  url: https://helm.traefik.io/traefik
requires:
- chart: traefik/traefik
  version: 9.10.1
version: 1
```
