### ISSUE TITLE
Charttool issues if the directory already exists

### ISSUE THREAD

**Issue by Temikus** [grafana/tanka#454]
**Version:**

```
λ tk --version
tk version v0.13.0
```

**Repro:**

1) Init charts:
```
tk tool charts init
```
2) Try adding a chart from a repo that's already added to helm:
```
λ tk tool charts add longhorn/longhorn@1.1.0                                                                                                                                                                                               Adding 1 Charts ...
 OK: longhorn/longhorn@1.1.0
Added 1 Charts to helmfile.yaml. Vendoring ...
Syncing Repositories ...
Pulling Charts ...
reading chart manifest: open .../k8s/charts/longhorn/Chart.yaml: no such file or directory
```
3) Try vendoring separately:
```
λ tk tool charts vendor                                                                                                                                                                                                   
Syncing Repositories ...
Pulling Charts ...
reading chart manifest: open .../k8s/charts/longhorn/Chart.yaml: no such file or directory
```
3) Realise I need to add `longhorn` repo to `chartfile.yaml`:
```
directory: charts
repositories:
- name: stable
  url: https://charts.helm.sh/stable
- name: longhorn
  url: https://charts.longhorn.io
requires:
- chart: longhorn/longhorn
  version: 1.1.0
version: 1
```
4)  Try vendoring again:

**EXPECTED RESULT:**

- Chart is downloaded into currently empty `charts/longhorn` directory.

**ACTUAL RESULT:**

```
λ tk tool charts vendor                                                                                                                                                                                                   
Syncing Repositories ...
Pulling Charts ...
reading chart manifest: open .../k8s/charts/longhorn/Chart.yaml: no such file or directory
```

**WORKAROUND:**
- Delete the `.../k8s/charts/longhorn` directory and invoke `tk tool charts vendor` again.
