### ISSUE TITLE
apiServer field does not support clusters that share hostname/port

### ISSUE THREAD

**Issue by Nashluffy** [grafana/tanka#686]
This is basically a rehash of what I mentioned on this [closed issue](https://github.com/grafana/tanka/issues/58#issuecomment-1054952428). The last time support for specifying context names or cluster names was mentioned, the argument was made that

> Only an IP really uniquely identifies a cluster.

This does not hold true in our production environments. 

We use [teleport](https://goteleport.com/) that acts as a proxy to our kube clusters. What this means is that all clusters share the same apiServer (hostname and port) as far as Tanka is concerned. It also disproves that an IP uniquely identifies a cluster. Here is what our "clusters" list looks like

```
Nash $ k config view
apiVersion: v1
kind: Config
clusters:
...
- cluster:
    certificate-authority-data: ...
    server: https://proxy-server:9999
  name: proxy-server
```

and then the actual context for "example-cluster" looks like
```
- context:
    cluster: proxy-server
    user: example-cluster-user
  name: example-cluster
```

Teleport does some magic with the user that it uses inside the app (I assume), but that's kinda beside the point. 

Our automation bypasses teleport and pulls a kubeconfig from our cloud provider. This means there can be multiple valid contexts for the same cluster.

If we had the ability to specify something like
```
    "contextNames": ["example-cluster", "example-cluster-automation"],
```
Tanka would work with Teleport. As of now it does not work, unfortunately. Perhaps `contextNames` or something similar could be added, with docs noting the use/warnings?
