### ISSUE TITLE
Template environment substitution (e.g. from Flux) breaks Kubernetes Secrets

### ISSUE THREAD

**Issue by xvzf** [grafana/tanka#687]
We're using [Flux Substitution](https://fluxcd.io/docs/components/kustomize/kustomization/#variable-substitution) in combination with `tk export` in order to pass in some externally managed references and _template secrets out of other secrets_

e.g. the tanka rendered manifest
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: test
stringData:
  TEST_INT: ${SOME_INT}
```

with the variable `SOME_INT="1234"` would be substituted to 
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: test
stringData:
  TEST_INT: 1234
```
which is not a valid Kubernetes secret. With Kustomize I used to prevent this by quoting those references:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: test
stringData:
  TEST_INT: "${SOME_INT}"
```

Is this something worth exploring Tanka or an edge case you don't want to support? As mitigation we're now setting `SOME_INT="'1234'"` which is not very elegant :-)

**Comment by Duologic** [comment]
Do you have some jsonnet example that i can use to reproduce?

**Comment by xvzf** [comment]
sure!
```jsonnent
local k = (import 'k.libsonnet');

{
  secret:
    k.core.v1.secret.new('test', {})
    + k.core.v1.secret.withStringData({
      TEST_INT: '${SOME_INT}',
    }),
}
```

renders to:
```
apiVersion: v1
data: {}
kind: Secret
metadata:
  name: test
  namespace: default
stringData:
  TEST_INT: ${SOME_INT}
type: Opaque
```
