### ISSUE TITLE
tool/charts: Allow 2 or more versions of the same chart

### ISSUE THREAD

**Issue by bcbrockway** [grafana/tanka#778]
This feature was alluded to in https://github.com/grafana/tanka/issues/508 but only validation was added in the end to prevent conflicts. We'd really like to be able to specify 2 versions of the same chart in the same repo since we have multiple Environments using it at the same time and it would be nice to be able to promote chart upgrades through them rather than having to update them all at once.

**Comment by julienduchesne** [comment]
You can, you have to specify different directories:

```yaml
directory: charts
repositories:
- name: fluxcd-community
  url: https://fluxcd-community.github.io/helm-charts
requires:
- chart: fluxcd-community/flux2
  version: 1.2.0
  directory: '1.2.0'
- chart: fluxcd-community/flux2
  version: 1.6.0
  directory: '1.6.0'
version: 1
```

Still needs to be documented
