### ISSUE TITLE
tk using wrong kubeconfig context?

### ISSUE THREAD

**Issue by strowi** [grafana/tanka#780]
Hi,

i just stumbled upon the following weird behaviour when adding a 2nd context to the kubeconfig, having the name of the first as suffix.

E.g.:
- context abc
- context arn:aws:eks:eu-central-1:XXXXXX:cluster/abc

Runnng tk commands on the first cluster will be applied to the 2nd. 
My guess would be this is related to the naming of EKS clusters and parsing of the kubeconfig. 

`tk diff environments/abc` & co was working fine with my existing cluster context "abc":

```json
{
  "apiVersion": "tanka.dev/v1alpha1",
  "kind": "Environment",
  "metadata": {
    "name": "environments/abc"
  },
  "spec": {
    "apiServer": null,
    "contextNames": [
      "abc"
    ],
    "namespace": "test",
    "resourceDefaults": {},
    "diffStrategy": "native",
    "expectVersions": {},
    "injectLabels": true
  }
}
```

But when i added a new aws-eks context it seems tk always selects that one instead of "abc":

```yaml
- context:
    cluster: abc
    user: abc
  name: abc

- context:
    cluster: arn:aws:eks:eu-central-1::XXXXXX:cluster/abc
    user: arn:aws:eks:eu-central-1:XXXXXX:cluster/abc
  name: arn:aws:eks:eu-central-1:XXXXXX:cluster/abc
```

```bash
# tk version v0.22.1
~> tk diff environments/abc
# this error happens because i deleted the cluster, but shows it wants to check the wrong one...

Unable to connect to the server: dial tcp: lookup XXXXX.gr7.eu-central-1.eks.amazonaws.com on 127.0.0.53:53: no such host
Error: connecting to Kubernetes: obtaining versions: exit status 1
```

regards,
strowi
