### ISSUE TITLE
Helm tool credentials management for private repo charts

### ISSUE THREAD

**Issue by mogaika** [grafana/tanka#922]
If I not mistaken, when using `tk tool charts vendor` you have to pass repo credentials via `chartfile.yaml`:
```
repositories:
- name: repo-private
  url: https://registry.___com/chartrepo/___
  username: XXXXXXXXX
  password: XXXXXXXXX
```
This is not acceptable from security perspective, since different users usually require different credentials and this way this file should be always modified and not commited.

Possible solution:
Add `--repository-config` (as in helm) to `tk tool charts vendor` to be able to use local `~/.config/helm/repositories.yaml`. This way repositories management will be done by user and `chartfile.yaml` with `tk tool charts vendor` will be used only for charts management and there will be no need to pass auth parameters around to tanka. Feels more like workaround, but it's simple and preserves chart management of `chartfile.yaml`, especially considering that usually repo names and url associations are the same between different users anyways.
