### ISSUE TITLE
Keep comments in chartfile.yaml?

### ISSUE THREAD

**Issue by strowi** [grafana/tanka#955]
Hi,

the commands `tk tool charts (add-repo|add` update the chartfile and remove ALL comments. This might not be desired or expected.
Would it be possible to change the command to keep comments in the file?

Further explanation: we are using renovate-bot to manage almost all updates in our code, including tanka/charts. Therefore we added a regex to be able to use comments in the `chartfile.yaml` to detect and update:

```yaml
requires:
  - chart: renovate/whitesource-renovate
    # renovate: datasource=helm depName=whitesource-renovate registryUrl=https://mend.github.io/renovate-on-prem versioning=helm
    version: 4.1.0
....
```
But these useful comments would be removed on add/add-repo..
