### ISSUE TITLE
Cannot define a TCP port and a UDP port when both use the same port number

### ISSUE THREAD

**Issue by beorn7** [grafana/tanka#99]
See https://github.com/grafana/jsonnet-libs/pull/178 for an example. In short:
Alertmanager gossiping, similar to DNS, uses both UDP and TCP (presumably the latter as a fallback for the former). In K8s (and with ksonnet), it is no problem to define two ports with different protocol and name for the same port number. The example linked above results in the following port definition with `ks`:

```jsonnet
     "ports": [
       {
         "name": "alertmanager-http-metrics",
         "port": 80,
         "targetPort": 80
       }
       {
         "name": "alertmanager-gossip-udp",
         "port": 9094,
         "protocol": "UDP",
         "targetPort": 9094
       }
       {
         "name": "alertmanager-gossip-tcp",
         "port": 9094,
         "targetPort": 9094
       }
     ],
```

Doing the same thing with `tk` munges together the both alertmanager-gossip-… ports. The result is different depending on the order the two ports are defined. I assume this has to do with the way Tanka flattens the result.

**Comment by beorn7** [comment]
Actually, `tk show` is showing the right thing as above, just `tk diff` is giving me the weird result. So perhaps the problem is only in the diff'ing, and Tanka would send the right thing to K8s.

**Comment by sh0rez** [comment]
We have two diff strategies at the moment:`native` (`kubectl diff`) and `subset` for older clusters lower than v1.13. I suspect this issue to only occur in subset mode, could you check the cluster version?

**Comment by beorn7** [comment]
The K8s API server is v1.13.7. That's not “lower than v1.13”. (Or did you mean "v1.13 or lower”?)

**Comment by sh0rez** [comment]
Odd. Version is fine. Please try forcing the diff strategy using flag to native, if that doesn’t help try piping tk show into kubectl diff ... if THAT doesn’t help either it’s a kubectl issue

**Comment by beorn7** [comment]
Did all of that. Result: This is a kubectl issue!

Excerpts from `tk show`:
```yaml
spec:
  ports:
  - name: alertmanager-http-metrics
    port: 80
    targetPort: 80
  - name: alertmanager-gossip-udp
    port: 9094
    protocol: UDP
    targetPort: 9094
  - name: alertmanager-gossip-tcp
    port: 9094
    targetPort: 9094
  selector:
    name: alertmanager
// ...
       ports:
        - containerPort: 80
          name: http-metrics
        - containerPort: 9094
          name: gossip-udp
          protocol: UDP
        - containerPort: 9094
          name: gossip-tcp
```

Ran `kubectl diff` on that output:
```
--- /tmp/LIVE-630995268/apps.v1beta1.StatefulSet.default.alertmanager   2019-10-27 22:10:02.768325693 +0100
+++ /tmp/MERGED-224906195/apps.v1beta1.StatefulSet.default.alertmanager 2019-10-27 22:10:02.880327719 +0100
@@ -43,6 +52,9 @@
         - containerPort: 80
           name: http-metrics
           protocol: TCP
+        - containerPort: 9094
+          name: gossip-udp
+          protocol: UDP
         resources:
           requests:
             cpu: 10m
# ...
--- /tmp/LIVE-630995268/v1.Service.default.alertmanager 2019-10-27 22:09:57.544231823 +0100
+++ /tmp/MERGED-224906195/v1.Service.default.alertmanager       2019-10-27 22:09:57.656233821 +0100
@@ -19,6 +19,10 @@
     port: 80
     protocol: TCP
     targetPort: 80
+  - name: alertmanager-gossip-udp
+    port: 9094
+    protocol: UDP
+    targetPort: 9094
   selector:
     name: alertmanager
   sessionAffinity: None
exit status 1
```

We found a `kubectl diff` bug! :o)
